services:
  db:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senha1
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306:3306
      - 33060:33060
    networks:
      - lan      

  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - wp_data:/var/www/html    
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - lan      

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db      
    networks:
      - lan      

volumes:
  db_data:
  wp_data:      

networks:
  lan: